### PR TITLE
MARLIN ESPD3D

### PR DESCRIPTION
**Pull request by So6Rallye**
Enable esp3d for marlin firmware 2.0.7.2

### CODE REVIEW

**Comment by So6Rallye** [comment]
how to enable ESP3D module with marlin 2.0.7.2.

**Comment by So6Rallye** [comment]
add tutorial esp3d enable in English and French and add same tutorial for Marlin 2.0.7.2 with original screen

**Comment by jdegenstein** [comment]
Hello, thank you very much for the work you have put into this. I did have a question about an inconsistency in the file "TUTORIAL MARLIN ENGLISH.pdf" on page 2. The screenshot shows:

`//#define WIFISUPPORT
//#define ESP3D_WIFISUPPORT`

this is followed by the text "don't uncomment"

which is then followed by the code:
`//#define WIFISUPPORT
#define ESP3D_WIFISUPPORT`

I feel the latter is correct, but the former two statements imply that both lines should be commented. Please advise.

Thank you

**Comment by So6Rallye** [comment]
Hello, yes these 2 line doesn't work on marlin 2.0.7.2 . The firmware won't compil. I've checked that issue with BTT Tony on facebook and finally I've found the solution. All People on youtube have try this board without wifi because he can't make it work.First compil firmware marlin with these 2 line /#define WIFISUPPORT
//#define ESP3D_WIFISUPPORT`inject in SDcard and download into printer.Now printer work without wifi on marlin 2.0.7.2Second compil esp3d firmware with esp07s settings, compil and inject in sdcard too and download into printerNow printer say IP adress and work with wifi esp8266 esp07s and ESP3D webui.I can provide firmware if you want. I'm actually in work on marlin 2.0.8 with idex expensions e3 rrf board and wifi, i've compil it without issues. I'm just waiting the parts to try and when is done, i provide this solution too.Don't hésitante if you want more détail.ThanksEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : jdegenstein ***@***.***> Date : 03/05/2021  20:29  (GMT+01:00) À : bigtreetech/BTT-E3-RRF ***@***.***> Cc : So6Rallye ***@***.***>, Manual ***@***.***> Objet : Re: [bigtreetech/BTT-E3-RRF] MARLIN ESPD3D (#15) 
Hello, thank you very much for the work you have put into this. I did have a question about an inconsistency in the file "TUTORIAL MARLIN ENGLISH.pdf" on page 2. The screenshot shows:
`//#define WIFISUPPORT
//#define ESP3D_WIFISUPPORT`
this is followed by the text "don't uncomment"
which is then followed by the code:
`//#define WIFISUPPORT
#define ESP3D_WIFISUPPORT`
I feel the latter is correct, but the former two statements imply that both lines should be commented. Please advise.
Thank you

**Comment by jdegenstein** [comment]
Thanks for the response. I compiled ESP3D from source to create the ESP3D.bin file. Unfortunately the release version of 2.1.1 ESP3D no longer compiles correctly with VSCode/PlatformIO. I checked out the development version 2.1.x from github and I was able to compile this with the following platformio.ini section:

~~~
[env:esp07s]
platform = espressif8266@2.6.3
platform_packages      = toolchain-xtensa@2.40802.200502
board = esp07s
framework = arduino
monitor_speed = 115200
monitor_flags = --echo
monitor_filters = colorize
; set frequency to 80MHz
board_build.f_cpu = 80000000L
; set frequency to 40MHz
board_build.f_flash = 40000000L
board_build.flash_mode = qio
upload_resetmethod = nodemcu
upload_speed = 115200
lib_ignore = 
    AsyncTCP
    ESP32NetBIOS
    ESP32SSPD
~~~

I can confirm that ESP3D_WIFISUPPORT is NOT needed in Configuration_adv.h to use ESP3D, this is apparently intended for using an ESP32 as the main printer microcontroller (go figure on the naming).

```
//#define WIFISUPPORT
//#define ESP3D_WIFISUPPORT
```

I made another change to your procedure to enable two UARTs:
```
#define SERIAL_PORT 1
#define SERIAL_PORT_2 3
```

I am using baudrate of 921600 and it is working well.

John

**Comment by So6Rallye** [comment]
Nice thanks for your return too. Serial port for me is the same like bigtreetech said. Maybe for original screen and baudrate stock of ender 3.

Why do you need two uart ?

**Pull request merged**
